---
title: "Mix code to explore gis data with python and R"
author: "Tainá Rocha"
date: "22/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("reticulate")) 
  install.packages("reticulate")
if (!require("tidyverse")) 
  install.packages("tidyverse")
if (!require("glue")) 
  install.packages("glue")
if (!require("remotes")) 
  install.packages("remotes")
if (!require("rminiconda")) 
  install_github("hafen/rminiconda")
packageVersion("reticulate")

```
Testes Python e R

```{r}
eu_gosto_de_R <- "nossa, como você é legal!"
eu_gosto_de_R
```


```{python}
eu_gosto_de_python = "tudo bem, vida que segue" ## KKK só um teste gente
print(eu_gosto_de_python)
```
Lendo objetos do python no R, carregando pelo reticulate:
```{r}
library(reticulate)
veio_do_python <- py$eu_gosto_de_python
paste(veio_do_python, " Segue no R.")

```
Ler objetos do R no python usando o objeto R.
'''
```{python}
print(r.eu_gosto_de_R+" Também no python.")
```
